### PR TITLE
Update P1389.apln

### PR DESCRIPTION
**Pull request by soveran**
This solution seems to work with GNU APL.

Before opening a pull request to add your solutions to this repository,
please **go over the following checklist**:

 - [X] I tested my solutions with the respective test cases from the LeetCode.com website;
 - [ ] I added a couple of comments with an overview of how my solutions work;
   - [ ] I included my GitHub nickname (optional);
 - [ ] My solutions were added at the _bottom_ of the solutions that already existed;
 - [ ] I added my solutions to the runtime comparison tradfns, when such tradfns were present.

### CODE REVIEW

**Comment by RojerGS** [comment]
Hey there, thanks for your submission!

Your solution doesn't seem to work; consider the following test case:

```APL
      0 0 1 {∊⌽¨(1+⍺[⍋⍺])⊂⍵[⍋,⍺]}'abc'
bac
```

The correct answer should be `'bca'`.

**Review by RojerGS — CHANGES_REQUESTED** [review]
As per my comment, the solution unfortunately doesn't work yet.

Also, when you fix your submission, please _add_ it next to the others, instead of replacing what's already there :)

**Comment by soveran** [comment]
> Unfortunately, LeetCode's basic test cases don't show this type of situation, but this is the thing that is very hard to tackle, in my opinion... If you figure out how to fix it, let me know!

Hey Rodrigo, thanks for you reply :-)

I think the problem as stated is about numbers: "Given two arrays of integers `nums` and `index`. Your task is to create _target_ array under the following rules". Sorry for replacing the solution, my bad!

**Comment by RojerGS** [comment]
> I think the problem as stated is about numbers.

Absolutely right, but in your APL solution, the data can be numbers or anything else, your solution is general enough. If you replace `'abc'` with `1 2 3` or any numeric vector you wish, you will find it still fails if the insertion order is the one in my example.

**Comment by soveran** [comment]
I see it now, closing the PR :-)

**Pull request closed without merging**
